SELECT SUM(PURCHASE_AMOUNT) AS TOTAL_PURCHASE_AMT FROM orders;
SELECT AVG(PURCHASE_AMOUNT) AS AVG_PURCHASE_AMT FROM ORDERS;
SELECT MAX(PURCHASE_AMOUNT) AS MAX_PURCHASE_AMT FROM ORDERS;
SELECT MIN(PURCHASE_AMOUNT) AS MIN_PURCHASE_AMT FROM ORDERS;
SELECT COUNT(distinct salesman_id) AS COUNT_SALESMAN FROM ORDERS;